/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analisiskevin;

import javax.swing.JOptionPane;

/**
 *
 * @author kevin Figueroa
 */
public class frmLiteralA extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmLiteralA() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Tartaglia-Cardano");
    }

//    public static double[] discriminante(double a, double b, double c) {
//        double h, g, d;
//        h = (3 * b - Math.pow(a, 2)) / 9;
//        g = (9 * a * b - 27 * c - 2 * Math.pow(a, 3)) / 54;
//        d = Math.pow(g, 2) + Math.pow(h, 3);
//
//        double valores[] = {d, h, g};
//        return valores;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbOpcion = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnSolucionA = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultadoMuller = new javax.swing.JTextArea();
        btnMuller1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultadoMuller1 = new javax.swing.JTextArea();
        btnMuller2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        SolucionTartaglia = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtR2 = new javax.swing.JTextField();
        txtR1 = new javax.swing.JTextField();
        txtR3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtRi4 = new javax.swing.JTextField();
        txtRi5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtR1_2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtR2_2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtRi1_2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtR3_2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtRi2_2 = new javax.swing.JTextField();
        SolucionTartaglia2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btnHorner1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtError2Horner = new javax.swing.JTextField();
        txtRaiz1Horner = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtRaiz2Horner = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        btnHorner2 = new javax.swing.JButton();
        txtError1Horner = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("X³+3x-1=0");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/A).png"))); // NOI18N
        jLabel2.setText("jLabel2");

        cmbOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno [...]", "Tartaglia-Cardano", "Horner", "Muller", "Bairstow" }));
        cmbOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOpcionActionPerformed(evt);
            }
        });

        jLabel3.setText("Generar solución mediante:");

        btnSolucionA.setText("IR A LA SOLUCION");
        btnSolucionA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolucionAActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel16.setText("X³-4.65x²-49.92x-76.69=0");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/a_2.png"))); // NOI18N
        jLabel17.setText("jLabel17");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(btnSolucionA)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel16))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(cmbOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSolucionA)
                .addGap(74, 74, 74))
        );

        panel.addTab("Principal", jPanel1);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setText("X³+3x-1=0");

        txtResultadoMuller.setColumns(20);
        txtResultadoMuller.setRows(5);
        jScrollPane1.setViewportView(txtResultadoMuller);

        btnMuller1.setText("Generar Solucion 1");
        btnMuller1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuller1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setText("X³-4.65x²-49.92x-76.69=0");

        txtResultadoMuller1.setColumns(20);
        txtResultadoMuller1.setRows(5);
        jScrollPane2.setViewportView(txtResultadoMuller1);

        btnMuller2.setText("Generar Solucion 2");
        btnMuller2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuller2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(btnMuller1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(btnMuller2))
                .addGap(94, 94, 94))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(564, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMuller1)
                    .addComponent(btnMuller2))
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(178, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(160, 160, 160)))
        );

        panel.addTab("Muller", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("X³+3x-1=0");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        SolucionTartaglia.setText("Solución tartaglia 1");
        SolucionTartaglia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolucionTartagliaActionPerformed(evt);
            }
        });
        jPanel2.add(SolucionTartaglia, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 252, -1, -1));

        jLabel5.setText("X1:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 95, -1, -1));

        jLabel6.setText("X2:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 142, -1, -1));

        jLabel7.setText("X3:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 188, -1, -1));
        jPanel2.add(txtR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 140, 150, -1));
        jPanel2.add(txtR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 93, 216, -1));
        jPanel2.add(txtR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 186, 150, -1));

        jLabel8.setText("+");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        jLabel9.setText("-");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        txtRi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRi4ActionPerformed(evt);
            }
        });
        jPanel2.add(txtRi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 143, -1));
        jPanel2.add(txtRi5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 143, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("X³-4.65x²-49.92x-76.69=0");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 12, -1, -1));

        jLabel11.setText("X1:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 95, -1, -1));
        jPanel2.add(txtR1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 93, 216, -1));

        jLabel12.setText("X2:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 142, -1, -1));
        jPanel2.add(txtR2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 140, 170, -1));

        jLabel13.setText("+");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 142, -1, -1));

        txtRi1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRi1_2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtRi1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 143, -1));

        jLabel14.setText("X3:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 188, -1, -1));
        jPanel2.add(txtR3_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 186, 162, -1));

        jLabel15.setText("-");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 188, -1, -1));

        txtRi2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRi2_2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtRi2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 186, 143, -1));

        SolucionTartaglia2.setText("Solución tartaglia 2");
        SolucionTartaglia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolucionTartaglia2ActionPerformed(evt);
            }
        });
        jPanel2.add(SolucionTartaglia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 252, -1, -1));

        panel.addTab("Tartaglia-Cardano", jPanel2);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel20.setText("X³+3x-1=0");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        btnHorner1.setText("Solución Horner 1");
        btnHorner1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorner1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnHorner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jLabel21.setText("Raíz:");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel22.setText("Error:");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel4.add(txtError2Horner, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 210, -1));
        jPanel4.add(txtRaiz1Horner, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 216, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel26.setText("X³-4.65x²-49.92x-76.69=0");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 12, -1, -1));

        jLabel27.setText("Raíz:");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));
        jPanel4.add(txtRaiz2Horner, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 216, -1));

        jLabel28.setText("Error:");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        btnHorner2.setText("Solución Horner 2");
        btnHorner2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorner2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnHorner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, -1));
        jPanel4.add(txtError1Horner, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 210, -1));

        panel.addTab("Horner", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SolucionTartaglia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolucionTartaglia2ActionPerformed
        double a, b, c, cubo, x1 = 0, x2 = 0, x3 = 0;
        String resultado;
        cubo = 1;
        a = -4.65;
        b = -49.92;
        c = -76.69;

        if (cubo != 1) {
            a = a / cubo;
            b = b / cubo;
            c = c / cubo;
            cubo = 1;
        }
        double resp[] = ProcesoTarFerrari.tartaglia(a, b, c);
        //resultado= "Raiz 1:"+resp[0]+"Raiz 2:"+ resp[1]+"\n"+"Raiz 3:"+resp[2]+"+"+resp[3]+"i"+"Raiz 4:"+resp[2]+"-"+resp[3]+"i";
        //txtResultadoTar.setText(resultado);
        if (resp.length == 4) {
            txtRi1_2.setText(String.valueOf(resp[3]));
            txtRi2_2.setText(String.valueOf(resp[3]));
        }
        txtR1_2.setText(String.valueOf(resp[0]));
        txtR2_2.setText(String.valueOf(resp[1]));
        txtR3_2.setText(String.valueOf(resp[2]));
    }//GEN-LAST:event_SolucionTartaglia2ActionPerformed

    private void txtRi2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRi2_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRi2_2ActionPerformed

    private void txtRi1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRi1_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRi1_2ActionPerformed

    private void txtRi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRi4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRi4ActionPerformed

    private void SolucionTartagliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolucionTartagliaActionPerformed
        double a, b, c, cubo, x1 = 0, x2 = 0, x3 = 0;
        String resultado;
        cubo = 1;
        a = 0;
        b = 3;
        c = -1;

        if (cubo != 1) {
            a = a / cubo;
            b = b / cubo;
            c = c / cubo;
            cubo = 1;
        }
        double resp[] = ProcesoTarFerrari.tartaglia(a, b, c);
        //resultado= "Raiz 1:"+resp[0]+"Raiz 2:"+ resp[1]+"\n"+"Raiz 3:"+resp[2]+"+"+resp[3]+"i"+"Raiz 4:"+resp[2]+"-"+resp[3]+"i";
        //txtResultadoTar.setText(resultado);
        if (resp.length == 4) {
            txtRi4.setText(String.valueOf(resp[3]));
            txtRi5.setText(String.valueOf(resp[3]));
        }
        txtR1.setText(String.valueOf(resp[0]));
        txtR2.setText(String.valueOf(resp[1]));
        txtR3.setText(String.valueOf(resp[2]));
    }//GEN-LAST:event_SolucionTartagliaActionPerformed

    private void btnMuller2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuller2ActionPerformed
        double x0, x1, x2, x3, c;
        String Resultado="";
        String funcion = "x^3-(4.65*x^2)-(49.92*x)-79.69";
        //x^3 +3*x^2 +3*x +2
        //la entrada de exponente debe de ser con ^
        x0 =3;
        x1 = 4.5;
        x2 = 11;
        c = 3;
        Funcion ff = new Funcion(funcion);
        Muller mu = new Muller();
        double exp = 2 - c;
        double Err = (0.5) * Math.pow(10, exp);
        System.out.println("error=" + Err);
        //Secante sec = new Secante();
        double[] r = Muller.ABC(ff, x0, x1, x2, Err);
        Resultado += "Raiz: "+r[1]+"\n";
        Resultado +="Error: "+ r[0]+" \n";
        txtResultadoMuller.setText(Resultado);
    }//GEN-LAST:event_btnMuller2ActionPerformed

    private void btnMuller1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuller1ActionPerformed
        double x0, x1, x2, x3, c;
        String Resultado="";
        String funcion = "x^3+3*x-1";
        //x^3 +3*x^2 +3*x +2
        //la entrada de exponente debe de ser con ^
        x0 =0;
        x1 = 0.5;
        x2 = 1;
        c = 3;
        Funcion ff = new Funcion(funcion);
        Muller mu = new Muller();
        double exp = 2 - c;
        double Err = (0.5) * Math.pow(10, exp);
        System.out.println("error=" + Err);
        //Secante sec = new Secante();
        double[] r = Muller.ABC(ff, x0, x1, x2, Err);
        Resultado += "Raiz: "+r[1]+"\n";
        Resultado +="Error: "+ r[0]+" \n";
        txtResultadoMuller1.setText(Resultado);
        //txtResultadoMuller.setText(""+r[0]);
    }//GEN-LAST:event_btnMuller1ActionPerformed

    private void btnSolucionAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolucionAActionPerformed
        switch (cmbOpcion.getSelectedIndex()) {
            case 0:
            JOptionPane.showMessageDialog(null, "Seleccione un método para generar solución");
            break;
            case 1:
            panel.setSelectedIndex(1);
            break;
            case 2:
            break;
            case 3:
            break;
            case 4:
            break;
            default:
            break;
        }
    }//GEN-LAST:event_btnSolucionAActionPerformed

    private void cmbOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOpcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOpcionActionPerformed

    private void btnHorner1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorner1ActionPerformed
        String funcion ="X³+3x-1=0";
//        double [] coeficientes=Funcion.SacarCoeficientes(funcion);
        double [] coeficientes= new double[5];
        coeficientes[0]=0;
        coeficientes[1]=1;
        coeficientes[2]=0;
        coeficientes[3]=3;
        coeficientes[4]=-1;
        double Es=0.05;
        
        double x1=1;
        Horner h = new Horner();
        double [] rs= Horner.raizHorner(coeficientes, x1,Es);
        
        txtRaiz1Horner.setText(String.valueOf(rs[0]));
        txtError1Horner.setText(String.valueOf(rs[1]));
    }//GEN-LAST:event_btnHorner1ActionPerformed

    private void btnHorner2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorner2ActionPerformed
        String funcion ="X³-4.65x²-49.92x-76.69=0";
//        double [] coeficientes=Funcion.SacarCoeficientes(funcion);
        double [] coeficientes= new double[5];
        coeficientes[0]=0;
        coeficientes[1]=1;
        coeficientes[2]=-4.65;
        coeficientes[3]=-49.92;
        coeficientes[4]=-76.69;
        double Es=0.05;
        
        double x1=1;
        Horner h = new Horner();
        double [] rs= Horner.raizHorner(coeficientes, x1,Es);
        
        txtRaiz2Horner.setText(String.valueOf(rs[0]));
        txtError2Horner.setText(String.valueOf(rs[1]));
    }//GEN-LAST:event_btnHorner2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLiteralA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLiteralA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLiteralA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLiteralA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLiteralA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SolucionTartaglia;
    private javax.swing.JButton SolucionTartaglia2;
    private javax.swing.JButton btnHorner1;
    private javax.swing.JButton btnHorner2;
    private javax.swing.JButton btnMuller1;
    private javax.swing.JButton btnMuller2;
    private javax.swing.JButton btnSolucionA;
    private javax.swing.JComboBox<String> cmbOpcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JTextField txtError1Horner;
    private javax.swing.JTextField txtError2Horner;
    private javax.swing.JTextField txtR1;
    private javax.swing.JTextField txtR1_2;
    private javax.swing.JTextField txtR2;
    private javax.swing.JTextField txtR2_2;
    private javax.swing.JTextField txtR3;
    private javax.swing.JTextField txtR3_2;
    private javax.swing.JTextField txtRaiz1Horner;
    private javax.swing.JTextField txtRaiz2Horner;
    private javax.swing.JTextArea txtResultadoMuller;
    private javax.swing.JTextArea txtResultadoMuller1;
    private javax.swing.JTextField txtRi1_2;
    private javax.swing.JTextField txtRi2_2;
    private javax.swing.JTextField txtRi4;
    private javax.swing.JTextField txtRi5;
    // End of variables declaration//GEN-END:variables
}
