/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analisiskevin;

import org.nfunk.jep.JEP;

/**
 *
 * @author gochez
 */
public class frmLiteralD extends javax.swing.JFrame {

    /**
     * Creates new form frmLiteralD
     */
    public frmLiteralD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        SecanteD1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtResultadoSecante1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        SecanteD2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtResultadoSecante2 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtResultadoSecante3 = new javax.swing.JTextArea();
        SecanteD3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMullerD = new javax.swing.JTextArea();
        btnMullerD = new javax.swing.JButton();
        btnMullerD1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMullerD1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnMullerD2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMullerD2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/D_1.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("ln(1+x)-cos(x)=0");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/D_2.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("10sen(x)+3cos(x)=0");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno [...]", "Secante", "Muller" }));

        jButton1.setText("Ir a la Solución");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/D_3.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 23)); // NOI18N
        jLabel8.setText("e^(3(x-1))-ln(x-1)^2+1=0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(465, 465, 465)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(15, 15, 15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(92, 92, 92))
        );

        jTabbedPane1.addTab("Literal D", jPanel1);

        SecanteD1.setText("Generar Solucion Secante 1");
        SecanteD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecanteD1ActionPerformed(evt);
            }
        });

        txtResultadoSecante1.setColumns(20);
        txtResultadoSecante1.setRows(5);
        jScrollPane4.setViewportView(txtResultadoSecante1);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("ln(1+x)-cos(x)=0");

        SecanteD2.setText("Generar Solucion Secante 2");
        SecanteD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecanteD2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("10sen(x)+3cos(x)=0");

        txtResultadoSecante2.setColumns(20);
        txtResultadoSecante2.setRows(5);
        jScrollPane5.setViewportView(txtResultadoSecante2);

        txtResultadoSecante3.setColumns(20);
        txtResultadoSecante3.setRows(5);
        jScrollPane6.setViewportView(txtResultadoSecante3);

        SecanteD3.setText("Generar Solucion Secante 3");
        SecanteD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecanteD3ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setText("e^(3(x-1))-ln(x-1)^2+1=0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SecanteD1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SecanteD2)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SecanteD3)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(53, 53, 53)
                        .addComponent(SecanteD3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(53, 53, 53)
                            .addComponent(SecanteD2)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(53, 53, 53)
                            .addComponent(SecanteD1)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Método de la secante", jPanel2);

        txtMullerD.setColumns(20);
        txtMullerD.setRows(5);
        jScrollPane1.setViewportView(txtMullerD);

        btnMullerD.setText("Generar Solución muller 1");
        btnMullerD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMullerDActionPerformed(evt);
            }
        });

        btnMullerD1.setText("Generar Solución muller 2");
        btnMullerD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMullerD1ActionPerformed(evt);
            }
        });

        txtMullerD1.setColumns(20);
        txtMullerD1.setRows(5);
        jScrollPane2.setViewportView(txtMullerD1);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("ln(1+x)-Cos(x)=0");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("10Sin(x)+3Cos(x)=0");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("e^(3(x-1))-ln(x-1)^2+1=0");

        btnMullerD2.setText("Generar Solución muller 3");
        btnMullerD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMullerD2ActionPerformed(evt);
            }
        });

        txtMullerD2.setColumns(20);
        txtMullerD2.setRows(5);
        jScrollPane3.setViewportView(txtMullerD2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMullerD)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMullerD1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMullerD2)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(29, 29, 29)
                        .addComponent(btnMullerD2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnMullerD1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnMullerD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Método de muller", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnMullerDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMullerDActionPerformed

        double x0, x1, x2, x3, c;
        String Resultado = "";
        String funcion = "(ln(1+x)-cos(x))";
        //x^3 +3*x^2 +3*x +2
        //la entrada de exponente debe de ser con ^
        x0 = 0;
        x1 = 0.2;
        x2 = 1;
        c = 3;
        Funcion ff = new Funcion(funcion);
        Muller mu = new Muller();
        double exp = 2 - c;
        double Err = (0.5) * Math.pow(10, exp);
        System.out.println("error=" + Err);
        //Secante sec = new Secante();
        double[] r = Muller.ABC(ff, x0, x1, x2, Err);
        Resultado += "Raiz: " + r[1] + "\n";
        Resultado += "Error: " + r[0] + " \n";
        txtMullerD.setText(Resultado);
        //txtResultadoMuller.setText(""+r[0]);

    }//GEN-LAST:event_btnMullerDActionPerformed

    private void btnMullerD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMullerD1ActionPerformed
//"10*(sin(x))+3*cos(x)"

        double x0, x1, x2, x3, c;
        String Resultado = "";
        String funcion = "10*(sin(x))+3*cos(x)";
        //x^3 +3*x^2 +3*x +2
        //la entrada de exponente debe de ser con ^
        x0 = 3.5;
        x1 = 4.0;
        x2 = 5.0;
        c = 3;
        Funcion ff = new Funcion(funcion);
        Muller mu = new Muller();
        double exp = 2 - c;
        double Err = (0.5) * Math.pow(10, exp);
        System.out.println("error=" + Err);
        //Secante sec = new Secante();
        double[] r = Muller.ABC(ff, x0, x1, x2, Err);
        Resultado += "Raiz: " + r[1] + "\n";
        Resultado += "Error: " + r[0] + " \n";
        txtMullerD1.setText(Resultado);

    }//GEN-LAST:event_btnMullerD1ActionPerformed

    private void btnMullerD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMullerD2ActionPerformed

        double x0, x1, x2, x3, c;
        String Resultado = "";
        String funcion = "e^(3*x-3)-(ln(x-1)^2)+1";
        //x^3 +3*x^2 +3*x +2
        //la entrada de exponente debe de ser con ^
        x0 = 1.0;
        x1 = 1.1;
        x2 = 1.2;
        c = 3;
        Funcion ff = new Funcion(funcion);
        Muller mu = new Muller();
        double exp = 2 - c;
        double Err = (0.5) * Math.pow(10, exp);
        System.out.println("error=" + Err);
        //Secante sec = new Secante();
        double[] r = Muller.ABC(ff, x0, x1, x2, Err);
        Resultado += "Raiz: " + r[1] + "\n";
        Resultado += "Error: " + r[0] + " \n";
        txtMullerD2.setText(Resultado);

    }//GEN-LAST:event_btnMullerD2ActionPerformed

    private void SecanteD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecanteD1ActionPerformed
        String Resultado="";
        double x0, x1, c;
        //int c;
        String funcion;
        //la entrada de exponente debe de ser con ^^
        funcion = "(ln(1+x)-cos(x))";
        x0 = 0;
        x1 = 0.8;
        c = 3;
        double exp = 2 - c;
        double Err = (0.5) * Math.pow(10, exp);

        Funcion ff = new Funcion(funcion);
        Secante sec = new Secante();
        double[] r = sec.raiz(ff, x0, x1, Err);

        Resultado += "Raiz: " + r[0] + "\n";
        Resultado += "Error: " + r[1] + " \n";
        txtResultadoSecante1.setText(Resultado);
    }//GEN-LAST:event_SecanteD1ActionPerformed

    private void SecanteD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecanteD2ActionPerformed
        // 10sen(x)+3cos(x)=0
                String Resultado="";
        double x0, x1, c;
        //int c;
        String funcion;
        //la entrada de exponente debe de ser con ^^
        funcion = "10*(sin(x))+3*cos(x)";
        x0 = 4.5;
        x1 = 6.58;
        c = 3;
        double exp = 2 - c;
        double Err = (0.5) * Math.pow(10, exp);

        Funcion ff = new Funcion(funcion);
        Secante sec = new Secante();
        double[] r = sec.raiz(ff, x0, x1, Err);

        Resultado += "Raiz: " + r[0] + "\n";
        Resultado += "Error: " + r[1] + " \n";
        txtResultadoSecante2.setText(Resultado);
    }//GEN-LAST:event_SecanteD2ActionPerformed

    private void SecanteD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecanteD3ActionPerformed
                String Resultado="";
        double x0, x1, c;
        //int c;
        String funcion;
        //la entrada de exponente debe de ser con ^^
        funcion = "e^(3*x-3)-(ln(x-1)^2)+1";
        x0 = 0.8;
        x1 = 1.4;
        c = 3;
        double exp = 2 - c;
        double Err = (0.5) * Math.pow(10, exp);

        Funcion ff = new Funcion(funcion);
        Secante sec = new Secante();
        double[] r = sec.raiz(ff, x0, x1, Err);

        Resultado += "Raiz: " + r[0] + "\n";
        Resultado += "Error: " + r[1] + " \n";
        txtResultadoSecante3.setText(Resultado);    }//GEN-LAST:event_SecanteD3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLiteralD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLiteralD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLiteralD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLiteralD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLiteralD().setVisible(true);
            }
        });    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SecanteD1;
    private javax.swing.JButton SecanteD2;
    private javax.swing.JButton SecanteD3;
    private javax.swing.JButton btnMullerD;
    private javax.swing.JButton btnMullerD1;
    private javax.swing.JButton btnMullerD2;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txtMullerD;
    private javax.swing.JTextArea txtMullerD1;
    private javax.swing.JTextArea txtMullerD2;
    private javax.swing.JTextArea txtResultadoSecante1;
    private javax.swing.JTextArea txtResultadoSecante2;
    private javax.swing.JTextArea txtResultadoSecante3;
    // End of variables declaration//GEN-END:variables
}
